version: '3.7'

services:
  dfh-nginx:
    image: nginx:alpine
    container_name: dfh-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/ssl:/etc/nginx/ssl
      - ./config/nginx/includes:/etc/nginx/includes
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www
    depends_on:
      - dfh-prerenderer
    networks:
      defihelper:
        aliases:
          - backend-local.defihelper.io

  dfh-backend:
    image: node:16-alpine
    container_name: dfh-backend
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - ./src/defihelper-backend:/home/node/app
      - ./config/defihelper-backend.env:/home/node/app/.env
      - ./config:/config
    command: /bin/sh -c "npm ci && npm run build && npm run start"
    networks:
      defihelper:

  dfh-scanner:
    image: node:16-alpine
    container_name: dfh-scanner
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - ./src/defihelper-scanner:/home/node/app
      - ./config/defihelper-scanner.env:/home/node/app/.env
      - ./config:/config
    command: /bin/sh -c "npm ci && npm run server-build && npm run website-build && npm run start"
    networks:
      defihelper:

  dfh-app:
    image: node:16-alpine
    container_name: dfh-app
    working_dir: /home/node/app
    volumes:
      - ./src/defihelper-app:/home/node/app
      - ./config/defihelper-app.env:/home/node/app/.env
    command: /bin/sh -c "npm ci && npm run build"
    networks:
      defihelper:

  dfh-adapters:
    image: node:16-alpine
    container_name: dfh-adapters
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - ./src/defihelper-adapters:/home/node/app
    command: /bin/sh -c "npm ci && npm run watch"
    networks:
      defihelper:

  dfh-redis:
    image: redis:6.2.4-alpine
    container_name: dfh-redis
    restart: unless-stopped
    networks:
      defihelper:

  dfh-redisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: dfh-redisadmin
    restart: unless-stopped
    environment:
      REDIS_1_HOST: dfh-redis
    networks:
      defihelper:

  dfh-postgres:
    image: postgres:12.1
    container_name: dfh-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: development
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
      - ./pgsql/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      defihelper:

  dfh-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dfh-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@defihelper.io
      PGADMIN_DEFAULT_PASSWORD: dev
    volumes:
      - ./pgsql/servers.json:/pgadmin4/servers.json
    networks:
      defihelper:

  dfh-prerenderer:
    image: tvanro/prerender-alpine
    container_name: dfh-prerenderer
    restart: unless-stopped
    environment:
      - MEMORY_CACHE=0
      - CACHE_MAXSIZE=1000
      - CACHE_TTL=6000
    networks:
      defihelper:

#  dfh-mainnet:
#    image: ethereum/client-go
#    container_name: dfh-mainnet
#    restart: unless-stopped
#    command: --datadir=/root/.ethereum --syncmode full --gcmode archive --cache 73728 --http --http.api "eth,net,web3" --http.corsdomain '*' --http.vhosts '*' --http.addr 0.0.0.0 --http.port 8545 --ws --ws.addr 0.0.0.0
#    volumes:
#      - /data:/data
#      - ./data/mainnet:/root/.ethereum
#    networks:
#      bondappetit:

volumes:
  node_modules:

networks:
  defihelper:
