version: '3.7'

services:
  dfh-nginx:
    image: nginx:alpine
    container_name: dfh-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/ssl:/etc/nginx/ssl
      - ./config/nginx/includes:/etc/nginx/includes
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www
    depends_on:
      - dfh-prerenderer
    networks:
      defihelper:

  dfh-scan:
    image: node:14-alpine
    container_name: dfh-scan
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - ./src/blockchain-scan:/home/node/app
      - ./config/blockchain-scan.env:/home/node/app/.env
      - ./config:/config
    command: /bin/sh -c "npm ci && npm run server-build && npm run website-build && npm run start"
    networks:
      defihelper:

  dfh-postgres:
    image: postgres:12.1
    container_name: dfh-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: defihelper
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    networks:
      defihelper:

  dfh-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sharapp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@defihelper.io
      PGADMIN_DEFAULT_PASSWORD: dev
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      defihelper:

  dfh-prerenderer:
    image: tvanro/prerender-alpine
    container_name: dfh-prerenderer
    restart: unless-stopped
    environment:
      - MEMORY_CACHE=0
      - CACHE_MAXSIZE=1000
      - CACHE_TTL=6000
    networks:
      defihelper:

volumes:
  node_modules:
  pgadmin:

networks:
  defihelper:
